# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
notifications:
  email: false
julia:
  - nightly
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Logic"); Pkg.test("Logic"; coverage=true)'
after_success:
  - julia -e 'if VERSION >= v"0.4-"; cd(Pkg.dir("Logic")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); end'
